### ISSUE TITLE
Renderer service

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-core#4]
## General description

As a `user`, I expect to see a canvas with rendered components according to the layout that was taken from the workspace config.

## API

As `programmer` I expect to see a new business logic unit called as RendererService 

#### Design description

A clear and concise description of the design proposition.

- [] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases
https://github.com/capsulajs/capsulahub-core/pull/13

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes

**Comment by stephanebenayoun** [comment]
Following our conversation, here are the conclusions :


- Move what we called 'Layout config' to be in WorkspaceConfig.components.layout.config
- Move the specific logic of canvas creation to the canvas web component (creating the nodes/elements/tabs/etc)
- In this layout config, change `htmlTag` to `id`
- Update Layout API to 
```typescript
interface Renderer {
  randomPrefix: string; // ‘abc’

  renderLayout() {
    render(config.layout, ‘randomPrefix’+id)
  }
  renderItems() {
    config.items.foreach((item) => render(item, ‘randomPrefix’+id))
  }
  renderItem(id) {
    render(item, ‘randomPrefix’+id)
  }
} 
```
